### ISSUE TITLE
Run import.sh cannot load tLD.zip

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-deploy#49] opened 2023-10-18 13:54 UTC
When I am running import.sh I have following error on tLD stream.
Could not load http url: https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/tLD/2023-09-01/tLD.zip
The zip file is there on the server but the import cannot get it.

**Comment by jpiesing** [comment] 2023-10-18 14:03
This is a duplicate of https://github.com/cta-wave/Test-Content/issues/50.

**Comment by jpiesing** [comment] 2023-10-25 13:42
Ideally this should be addressed by ensuring database.json is correct. If that is too hard then import.sh could perhaps be changed to try dash-large if dash throws a 403.

**Comment by jpiesing** [comment] 2023-10-25 18:08
I've edited database.json to fix this issue but import.sh is picking up an old copy. Running './build.sh master latest --reload-tests' didn't make any difference.

**Comment by FritzHeiden** [comment] 2023-10-31 17:08
> I've edited database.json to fix this issue but import.sh is picking up an old copy. Running './build.sh master latest --reload-tests' didn't make any difference.

The version of the database.json inside the import.sh script is hardcoded to use a specific commit id. I will update it to the newest version

**Comment by FritzHeiden** [comment] 2023-10-31 19:04
Pushed changes to deploy and tests project for usage of tLD content

**Comment by louaybassbouss** [comment] 2023-11-06 15:32
@yanj-github  can you confirm that you can download tLD content and run the long duration test?

**Comment by jpiesing** [comment] 2023-11-06 16:32
> @yanj-github can you confirm that you can download tLD content and run the long duration test?

It downloaded all the files but them seemed to hang. When I did control-c, I got this backtrace which suggests it was just taking forever to unzip.

```
jon@jon-VirtualBox:~/dpctf-deploy$ fg
./import.sh
^CTraceback (most recent call last):
  File "/home/jon/dpctf-deploy/./download-content.py", line 148, in <module>
    main()
  File "/home/jon/dpctf-deploy/./download-content.py", line 61, in main
    zip.extractall(path=DEST_DIR)
  File "/usr/lib/python3.11/zipfile.py", line 1681, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/lib/python3.11/zipfile.py", line 1736, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/lib/python3.11/shutil.py", line 197, in copyfileobj
    buf = fsrc_read(length)
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/zipfile.py", line 955, in read
    data = self._read1(n)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/zipfile.py", line 1023, in _read1
    data += self._read2(n - len(data))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/zipfile.py", line 1055, in _read2
    data = self._fileobj.read(n)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/zipfile.py", line 775, in read
    data = self._file.read(n)
           ^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

```

**Comment by yanj-github** [comment] 2023-11-06 16:40
Download works for me finally got long duration content downloaded, but it used all allocated memory when processing and I cannot do anything else otherwise system hangs.

**Comment by yanj-github** [comment] 2023-11-06 17:03
When I run the test it starts fine but I have test timedout:
![image](https://github.com/cta-wave/dpctf-deploy/assets/59022223/83e880a0-ff21-4126-89a5-ce78ebb30d0c)

**Comment by jpiesing** [comment] 2023-11-06 18:54
Mine did eventually install, I just had to leave it and the computer alone for long enough.
It might be worth modifying import.sh to give some feedback while it's working, even if it's just printing a '.'

**Comment by FritzHeiden** [comment] 2023-11-06 19:00
I already extended the download script to account for the large file with progress update. Apparently I didn't push the changes. Will push them tomorrow



> When I run the test it starts fine but I have test timedout: 
Yes, the timeout will have to be adjusted accordingly for this test

**Comment by FritzHeiden** [comment] 2023-11-07 17:49
I had another look and saw that I did push the changes. I freshly cloned the deploy project and ran the import script. This is what it looks for me:
![image](https://github.com/cta-wave/dpctf-deploy/assets/9076000/e013c261-37f4-49bd-9cd3-79cbba49af98)

@jpiesing Can you confirm you pulled the latest changes?

**Comment by jpiesing** [comment] 2023-11-07 17:58
> I had another look and saw that I did push the changes. I freshly cloned the deploy project and ran the import script. This is what it looks for me: ![image](https://user-images.githubusercontent.com/9076000/281133051-e013c261-37f4-49bd-9cd3-79cbba49af98.png)
> 
> @jpiesing Can you confirm you pulled the latest changes?

Yes what you describe is exactly what happened until it got to 98.9% (or something like that).
After it got to 98.9%, it then sat there for 10s of minutes doing nothing visible. The python traceback above was perhaps 20-30-40 minutes after it got to 98.9%. What does it do after it has completed fetching all the files?

**Comment by FritzHeiden** [comment] 2023-11-07 18:06
It will unzip the content after downloading it. So I'll add progress report on unzipping aswell

**Comment by louaybassbouss** [comment] 2023-11-08 08:17
> It will unzip the content after downloading it. So I'll add progress report on unzipping aswell

@FritzHeiden  maybe you can add a message that download is completed and unzip content is started, which may take few minutes. Do you know about the progress of unzipping?

**Comment by FritzHeiden** [comment] 2023-11-08 16:45
I added indication for the extraction progress. As it is a little cumbersome to get the exact progress for this I am adding dots to `Extracting ...` as time goes on to hint that the process is still running.

**Comment by gitwjr** [comment] 2023-12-05 16:46
Closed.

**Closed by gitwjr** 2023-12-05 16:46 UTC
